# -*- coding: utf-8 -*-
"""biometrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h2Q7rfyBXy-UPQyjY-Cnlf86BKXJJLeB
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import altair as alt

sns.set(style="whitegrid", palette="muted", font_scale=1.2)

def load_and_clean(filename):
    df = pd.read_csv(filename)
    df.columns = df.columns.str.strip().str.lower()
    df['date'] = pd.to_datetime(df['date'], errors='coerce')
    return df

bio1 = load_and_clean("aadhar_bio_1.csv")
bio2 = load_and_clean("aadhar_bio_2.csv")
bio3 = load_and_clean("aadhar_bio_3.csv")
bio4 = load_and_clean("aadhar_bio_4.csv")

biometric_df = pd.concat([bio1, bio2, bio3, bio4], ignore_index=True)
print("Combined biometric dataset shape:", biometric_df.shape)
biometric_df.head()

# Univariate Analysis
age_summary = biometric_df[['bio_age_5_17','bio_age_17_']].sum().reset_index()
age_summary.columns = ['Age Group','Count']

fig = px.bar(age_summary, x='Age Group', y='Count',
             title="Univariate: Biometric Updates by Age Group",
             color='Age Group', text='Count')
fig.show()

# Bivariate Analysis
state_summary = biometric_df.groupby('state')[['bio_age_5_17','bio_age_17_']].sum().reset_index()

fig = px.bar(state_summary, x='state', y=['bio_age_5_17','bio_age_17_'],
             title="Bivariate: Biometric Updates by State & Age Group",
             labels={'value':'Count','state':'State','variable':'Age Group'},
             barmode='stack')
fig.update_layout(xaxis={'categoryorder':'total descending'})
fig.show()

# Trivariate Analysis
district_summary = biometric_df.groupby(['state','district'])[['bio_age_5_17','bio_age_17_']].sum().reset_index()

heatmap = alt.Chart(district_summary).mark_rect().encode(
    x='district:N',
    y='state:N',
    color='bio_age_5_17:Q',
    tooltip=['state','district','bio_age_5_17','bio_age_17_']
).properties(
    width=800,
    height=600,
    title="Trivariate: Heatmap of Biometric Updates (5–17 age group)"
)

heatmap.show()

# Anomaly Detection
# 1. Safe ratio calculation
biometric_df['ratio_17plus'] = biometric_df['bio_age_17_'] / (biometric_df['bio_age_5_17'].replace(0, 1))

# 2. Flag anomalies
anomalies = biometric_df[biometric_df['ratio_17plus'] > 2]

# 3. Summary
print("Number of anomalous districts:", len(anomalies))
print("Top 10 anomalies:")
print(anomalies[['state','district','pincode','bio_age_5_17','bio_age_17_','ratio_17plus']].head(10))

# visualization (only anomalies)
import plotly.express as px

fig = px.scatter(anomalies,
                 x='bio_age_5_17',
                 y='bio_age_17_',
                 color='ratio_17plus',
                 size='ratio_17plus',
                 hover_data=['state','district','pincode'],
                 title="Anomaly Detection: Districts with disproportionate adult updates (Filtered)")
fig.show()

#  Static plot
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
sns.scatterplot(data=anomalies, x='bio_age_5_17', y='bio_age_17_', hue='ratio_17plus')
plt.title("Anomaly Detection (Static)")
plt.show()

# Insight Extraction
# Overall totals
total_youth = biometric_df['bio_age_5_17'].sum()
total_adult = biometric_df['bio_age_17_'].sum()

# State with highest youth updates
top_youth_state = biometric_df.groupby('state')['bio_age_5_17'].sum().idxmax()
top_youth_value = biometric_df.groupby('state')['bio_age_5_17'].sum().max()

# State with highest adult updates
top_adult_state = biometric_df.groupby('state')['bio_age_17_'].sum().idxmax()
top_adult_value = biometric_df.groupby('state')['bio_age_17_'].sum().max()

# District anomalies
anomalies = biometric_df[biometric_df['ratio_17plus'] > 2]

print(" Key Insights:")
print(f"- Youth (5–17) biometric updates dominate nationally with {total_youth} vs {total_adult} adult updates.")
print(f"- {top_youth_state} has the highest youth updates ({top_youth_value}), suggesting strong school enrolment drives.")
print(f"- {top_adult_state} has the highest adult updates ({top_adult_value}), indicating focus on adult re-enrolments or corrections.")
print(f"- {len(anomalies)} districts show disproportionately high adult updates (ratio > 2), which may signal operational bottlenecks or targeted adult campaigns.")
print("- Geographic disparities suggest UIDAI could prioritize awareness in lagging districts.")

from google.colab import files
biometric_df.to_csv("biometric_master.csv", index=False)
files.download("biometric_master.csv")